"""add_article_favorites_table

Revision ID: 00037fbe887c
Revises: 9c422eafa504
Create Date: 2025-10-18 07:57:50.904476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00037fbe887c'
down_revision: Union[str, None] = '9c422eafa504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('favorited_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'article_id')
    )
    with op.batch_alter_table('article_favorites', schema=None) as batch_op:
        batch_op.create_index('idx_article_favorites', ['article_id'], unique=False)
        batch_op.create_index('idx_user_favorites', ['user_id', 'favorited_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_favorites', schema=None) as batch_op:
        batch_op.drop_index('idx_user_favorites')
        batch_op.drop_index('idx_article_favorites')

    op.drop_table('article_favorites')
    # ### end Alembic commands ###
