"""add newsletter_enabled column to users table

Revision ID: 0f0ebb099bf2
Revises: 466e2c578641
Create Date: 2025-10-20 21:36:27.055713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0ebb099bf2'
down_revision: Union[str, None] = '466e2c578641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add newsletter_enabled column with default value of True
    op.add_column('users', sa.Column('newsletter_enabled', sa.Boolean(), nullable=True, server_default='true'))
    # Update existing rows to set the default value
    op.execute("UPDATE users SET newsletter_enabled = true WHERE newsletter_enabled IS NULL")
    # Make the column NOT NULL after setting defaults
    op.alter_column('users', 'newsletter_enabled', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'newsletter_enabled')
    # ### end Alembic commands ###
