"""Add missing fields to viewpoint_relationships table

Revision ID: 2adc5be91fb4
Revises: 682aba524529
Create Date: 2025-10-21 02:25:11.930104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2adc5be91fb4'
down_revision: Union[str, None] = '682aba524529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
