"""add enhanced analyzer fields to viewpoint_relationships

Revision ID: 42b4c05de3af
Revises: 4c9b77dc4243
Create Date: 2025-10-21 05:25:01.838258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b4c05de3af'
down_revision: Union[str, None] = '4c9b77dc4243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewpoint_relationships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('how_this_opposes', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('why_this_opposes', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewpoint_relationships', schema=None) as batch_op:
        batch_op.drop_column('why_this_opposes')
        batch_op.drop_column('how_this_opposes')

    # ### end Alembic commands ###
