"""add_is_recommended_to_sources

Revision ID: 466e2c578641
Revises: 577958975249
Create Date: 2025-10-20 00:58:57.814885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466e2c578641'
down_revision: Union[str, None] = '577958975249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_recommended column to sources table, default existing sources to True
    op.add_column('sources', sa.Column('is_recommended', sa.Boolean(), nullable=False, server_default='true'))
    op.create_index(op.f('ix_sources_is_recommended'), 'sources', ['is_recommended'], unique=False)

    # Drop newsletter_enabled column from users (deprecated)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('newsletter_enabled')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore newsletter_enabled column to users
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newsletter_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # Remove is_recommended column from sources
    op.drop_index(op.f('ix_sources_is_recommended'), table_name='sources')
    op.drop_column('sources', 'is_recommended')

    # ### end Alembic commands ###
