"""Add framework analysis fields to viewpoint_relationships

Revision ID: 4c9b77dc4243
Revises: 2adc5be91fb4
Create Date: 2025-10-21 02:25:54.663651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9b77dc4243'
down_revision: Union[str, None] = '2adc5be91fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewpoint_relationships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('framework_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reasoning', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('primary_position', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('opposing_position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewpoint_relationships', schema=None) as batch_op:
        batch_op.drop_column('opposing_position')
        batch_op.drop_column('primary_position')
        batch_op.drop_column('reasoning')
        batch_op.drop_column('framework_name')

    # ### end Alembic commands ###
