"""add_newsletter_enabled_to_users

Revision ID: 577958975249
Revises: 00037fbe887c
Create Date: 2025-10-20 00:34:28.659731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577958975249'
down_revision: Union[str, None] = '00037fbe887c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable first
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newsletter_enabled', sa.Boolean(), nullable=True))

    # Step 2: Set default value for existing users (True = enabled by default)
    op.execute("UPDATE users SET newsletter_enabled = TRUE WHERE newsletter_enabled IS NULL")

    # Step 3: Make column non-nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('newsletter_enabled', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('newsletter_enabled')

    # ### end Alembic commands ###
