"""add_viewpoint_relationships_table

Revision ID: 682aba524529
Revises: 0f0ebb099bf2
Create Date: 2025-10-20 22:43:31.644686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682aba524529'
down_revision: Union[str, None] = '0f0ebb099bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewpoint_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_article_id', sa.Integer(), nullable=False),
    sa.Column('opposing_article_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('opposition_strength', sa.Float(), nullable=False),
    sa.Column('ai_explanation', sa.String(length=500), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('user_engagement_count', sa.Integer(), nullable=False),
    sa.Column('user_feedback_helpful', sa.Integer(), nullable=False),
    sa.Column('user_feedback_not_helpful', sa.Integer(), nullable=False),
    sa.Column('generation_method', sa.String(length=50), nullable=False),
    sa.Column('ai_model_version', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_regenerated', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opposing_article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['primary_article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('viewpoint_relationships', schema=None) as batch_op:
        batch_op.create_index('idx_active_relationships', ['is_active', 'created_at'], unique=False)
        batch_op.create_index('idx_expiration', ['expires_at', 'is_active'], unique=False)
        batch_op.create_index('idx_opposing_article', ['opposing_article_id'], unique=False)
        batch_op.create_index('idx_primary_article', ['primary_article_id'], unique=False)
        batch_op.create_index('idx_relationship_type', ['relationship_type'], unique=False)
        batch_op.create_index('idx_strength_order', ['opposition_strength', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_viewpoint_relationships_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewpoint_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viewpoint_relationships_is_active'))
        batch_op.drop_index('idx_strength_order')
        batch_op.drop_index('idx_relationship_type')
        batch_op.drop_index('idx_primary_article')
        batch_op.drop_index('idx_opposing_article')
        batch_op.drop_index('idx_expiration')
        batch_op.drop_index('idx_active_relationships')

    op.drop_table('viewpoint_relationships')
    # ### end Alembic commands ###
