"""add_unique_constraint_article_framework

Revision ID: 7e947d383738
Revises: c03e17942bf4
Create Date: 2025-10-12 16:08:22.976684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e947d383738'
down_revision: Union[str, None] = 'c03e17942bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_analysis', schema=None) as batch_op:
        batch_op.alter_column('political_lean',
               existing_type=postgresql.ENUM('left', 'center', 'right', name='politicallean'),
               nullable=True)
        batch_op.alter_column('stats_verification_status',
               existing_type=postgresql.ENUM('verified', 'unverified', 'disputed', 'false', name='verificationstatus'),
               nullable=True,
               existing_server_default=sa.text("'unverified'::verificationstatus"))
        batch_op.drop_index('ix_article_analysis_id')

    with op.batch_alter_table('article_frameworks', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_article_framework', ['article_id', 'framework_id'])

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('processing_status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::processingstatus"))
        batch_op.drop_index('ix_articles_id')

    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.drop_index('ix_frameworks_id')

    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.drop_index('ix_newsletters_id')

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index('ix_sources_id')
        batch_op.drop_index('ix_sources_rss_feed_url')
        batch_op.create_unique_constraint(None, ['rss_feed_url'])

    with op.batch_alter_table('statistic_verifications', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=postgresql.ENUM('verified', 'unverified', 'disputed', 'false', name='verificationstatus'),
               nullable=True,
               existing_server_default=sa.text("'unverified'::verificationstatus"))

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index('ix_topics_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('subscription_tier',
               existing_type=postgresql.ENUM('FREE', 'PREMIUM', name='subscriptiontier'),
               nullable=True,
               existing_server_default=sa.text("'FREE'::subscriptiontier"))
        batch_op.drop_index('ix_users_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_id', ['id'], unique=False)
        batch_op.alter_column('subscription_tier',
               existing_type=postgresql.ENUM('FREE', 'PREMIUM', name='subscriptiontier'),
               nullable=False,
               existing_server_default=sa.text("'FREE'::subscriptiontier"))

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index('ix_topics_id', ['id'], unique=False)

    with op.batch_alter_table('statistic_verifications', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=postgresql.ENUM('verified', 'unverified', 'disputed', 'false', name='verificationstatus'),
               nullable=False,
               existing_server_default=sa.text("'unverified'::verificationstatus"))

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_sources_rss_feed_url', ['rss_feed_url'], unique=True)
        batch_op.create_index('ix_sources_id', ['id'], unique=False)

    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.create_index('ix_newsletters_id', ['id'], unique=False)

    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.create_index('ix_frameworks_id', ['id'], unique=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('ix_articles_id', ['id'], unique=False)
        batch_op.alter_column('processing_status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::processingstatus"))

    with op.batch_alter_table('article_frameworks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_article_framework', type_='unique')

    with op.batch_alter_table('article_analysis', schema=None) as batch_op:
        batch_op.create_index('ix_article_analysis_id', ['id'], unique=False)
        batch_op.alter_column('stats_verification_status',
               existing_type=postgresql.ENUM('verified', 'unverified', 'disputed', 'false', name='verificationstatus'),
               nullable=False,
               existing_server_default=sa.text("'unverified'::verificationstatus"))
        batch_op.alter_column('political_lean',
               existing_type=postgresql.ENUM('left', 'center', 'right', name='politicallean'),
               nullable=False)

    # ### end Alembic commands ###
