"""add_user_submitted_articles

Revision ID: 9c422eafa504
Revises: 14a0e3209188
Create Date: 2025-10-18 05:07:42.243274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c422eafa504'
down_revision: Union[str, None] = '14a0e3209188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('articles', sa.Column('is_user_submitted', sa.Boolean(), nullable=True))
    op.add_column('articles', sa.Column('submitted_by_user_id', sa.Integer(), nullable=True))

    # Set default value for existing rows
    op.execute('UPDATE articles SET is_user_submitted = false WHERE is_user_submitted IS NULL')

    # Now make the column NOT NULL
    op.alter_column('articles', 'is_user_submitted', nullable=False)

    # Create index and foreign key
    op.create_index(op.f('ix_articles_is_user_submitted'), 'articles', ['is_user_submitted'], unique=False)
    op.create_foreign_key(None, 'articles', 'users', ['submitted_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_articles_is_user_submitted'))
        batch_op.drop_column('submitted_by_user_id')
        batch_op.drop_column('is_user_submitted')

    # ### end Alembic commands ###
