"""Add OAuth fields to users table only

Revision ID: add_oauth_fields_simple
Revises: 42b4c05de3af
Create Date: 2025-10-22 08:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'add_oauth_fields_simple'
down_revision: Union[str, None] = 'e7b694a129c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create oauth_accounts table
    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_data', sa.Text(), nullable=True),
    sa.Column('access_token', sa.String(length=1000), nullable=True),
    sa.Column('refresh_token', sa.String(length=1000), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Create indexes for oauth_accounts
    op.create_index('idx_oauth_provider_user', 'oauth_accounts', ['provider', 'provider_user_id'], unique=False)
    op.create_index('idx_oauth_user_provider', 'oauth_accounts', ['user_id', 'provider'], unique=False)
    op.create_index('ix_oauth_accounts_user_id', 'oauth_accounts', ['user_id'], unique=False)

    # Add OAuth columns to users table
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('oauth_provider_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('oauth_provider_data', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('oauth_avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('passwordless_login_enabled', sa.Boolean(), server_default='false', nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove OAuth columns from users table
    op.drop_column('users', 'passwordless_login_enabled')
    op.drop_column('users', 'oauth_avatar_url')
    op.drop_column('users', 'oauth_provider_data')
    op.drop_column('users', 'oauth_provider_id')
    op.drop_column('users', 'oauth_provider')

    # Drop indexes
    op.drop_index('ix_oauth_accounts_user_id', table_name='oauth_accounts')
    op.drop_index('idx_oauth_user_provider', table_name='oauth_accounts')
    op.drop_index('idx_oauth_provider_user', table_name='oauth_accounts')

    # Drop oauth_accounts table
    op.drop_table('oauth_accounts')

    # ### end Alembic commands ###