"""add_admin_panel_tables

Revision ID: bb65738374e1
Revises: e29da670f9de
Create Date: 2025-10-15 00:15:42.688771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb65738374e1'
down_revision: Union[str, None] = 'e29da670f9de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_execution_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('job_name', sa.String(length=200), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_data', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('api_calls_made', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_execution_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_execution_history_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_execution_history_started_at'), ['started_at'], unique=False)

    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_admin_email'), ['admin_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('admin_notes', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('last_admin_action', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_admin_action')
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_admin_email'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_action_type'))

    op.drop_table('admin_audit_logs')
    with op.batch_alter_table('job_execution_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_execution_history_started_at'))
        batch_op.drop_index(batch_op.f('ix_job_execution_history_job_id'))

    op.drop_table('job_execution_history')
    # ### end Alembic commands ###
