"""add statistics verification v2 fields and source credibility ratings

Revision ID: d819e76d0940
Revises: 1c75fe94a587
Create Date: 2025-10-03 00:07:10.475706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd819e76d0940'
down_revision: Union[str, None] = '1c75fe94a587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create source_credibility_ratings table
    op.create_table(
        'source_credibility_ratings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column('credibility_score', sa.Float(), nullable=False),
        sa.Column('is_academic', sa.Boolean(), nullable=False),
        sa.Column('is_government', sa.Boolean(), nullable=False),
        sa.Column('is_news_organization', sa.Boolean(), nullable=False),
        sa.Column('is_think_tank', sa.Boolean(), nullable=False),
        sa.Column('rating_method', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column('last_updated', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_credibility_ratings_domain'), 'source_credibility_ratings', ['domain'], unique=True)

    # Update statistic_verifications table
    with op.batch_alter_table('statistic_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
        batch_op.add_column(sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
        batch_op.add_column(sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
        batch_op.add_column(sa.Column('source_excerpt', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
        batch_op.add_column(sa.Column('source_credibility_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fact_check_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
        batch_op.add_column(sa.Column('fact_check_source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
        batch_op.add_column(sa.Column('fact_check_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
        batch_op.add_column(sa.Column('fact_check_details', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
        batch_op.add_column(sa.Column('last_checked', sa.DateTime(), nullable=True))
        batch_op.drop_column('verified_sources')
        batch_op.drop_column('notes')
        batch_op.drop_column('verified_by')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statistic_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_by', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('verified_sources', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('last_checked')
        batch_op.drop_column('fact_check_details')
        batch_op.drop_column('fact_check_url')
        batch_op.drop_column('fact_check_source')
        batch_op.drop_column('fact_check_status')
        batch_op.drop_column('source_credibility_score')
        batch_op.drop_column('source_excerpt')
        batch_op.drop_column('source_name')
        batch_op.drop_column('source_url')
        batch_op.drop_column('context')

    # Drop source_credibility_ratings table
    op.drop_index(op.f('ix_source_credibility_ratings_domain'), table_name='source_credibility_ratings')
    op.drop_table('source_credibility_ratings')

    # ### end Alembic commands ###
