"""enhance_article_clusters_for_event_tracking

Revision ID: e7b694a129c8
Revises: 42b4c05de3af
Create Date: 2025-10-22 03:24:51.142331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7b694a129c8'
down_revision: Union[str, None] = '42b4c05de3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewpoint_relationships', schema=None) as batch_op:
        batch_op.drop_index('idx_active_relationships')
        batch_op.drop_index('idx_expiration')
        batch_op.drop_index('idx_opposing_article')
        batch_op.drop_index('idx_primary_article')
        batch_op.drop_index('idx_relationship_type')
        batch_op.drop_index('idx_strength_order')
        batch_op.drop_index('ix_viewpoint_relationships_is_active')

    op.drop_table('viewpoint_relationships')
    with op.batch_alter_table('article_clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_signature', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('event_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('article_count', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('sources_count', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True, server_default=sa.text('now()')))
        batch_op.create_index(batch_op.f('ix_article_clusters_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_clusters_event_signature'), ['event_signature'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_clusters_event_signature'))
        batch_op.drop_index(batch_op.f('ix_article_clusters_event_date'))
        batch_op.drop_column('last_updated')
        batch_op.drop_column('sources_count')
        batch_op.drop_column('article_count')
        batch_op.drop_column('event_date')
        batch_op.drop_column('event_signature')

    op.create_table('viewpoint_relationships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('primary_article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('opposing_article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relationship_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('opposition_strength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ai_explanation', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_engagement_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_feedback_helpful', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_feedback_not_helpful', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ai_model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_regenerated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('framework_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reasoning', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('primary_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('opposing_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('how_this_opposes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('why_this_opposes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opposing_article_id'], ['articles.id'], name='viewpoint_relationships_opposing_article_id_fkey'),
    sa.ForeignKeyConstraint(['primary_article_id'], ['articles.id'], name='viewpoint_relationships_primary_article_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='viewpoint_relationships_pkey')
    )
    with op.batch_alter_table('viewpoint_relationships', schema=None) as batch_op:
        batch_op.create_index('ix_viewpoint_relationships_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_strength_order', ['opposition_strength', 'created_at'], unique=False)
        batch_op.create_index('idx_relationship_type', ['relationship_type'], unique=False)
        batch_op.create_index('idx_primary_article', ['primary_article_id'], unique=False)
        batch_op.create_index('idx_opposing_article', ['opposing_article_id'], unique=False)
        batch_op.create_index('idx_expiration', ['expires_at', 'is_active'], unique=False)
        batch_op.create_index('idx_active_relationships', ['is_active', 'created_at'], unique=False)

    # ### end Alembic commands ###
