"""add subscription system tables

Revision ID: f6ea9f284303
Revises: 31f70ab13ba5
Create Date: 2025-10-26 07:10:30.029844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6ea9f284303'
down_revision: Union[str, None] = '31f70ab13ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('billing_interval', sa.String(), nullable=False),
    sa.Column('features', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('trial_period_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_plans_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_plans_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_subscription_plans_stripe_price_id'), ['stripe_price_id'], unique=True)

    op.create_table('daily_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('analyses_count', sa.Integer(), nullable=False),
    sa.Column('api_calls_count', sa.Integer(), nullable=False),
    sa.Column('daily_analysis_limit', sa.Integer(), nullable=False),
    sa.Column('daily_api_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_usage_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_usage_user_id'), ['user_id'], unique=False)

    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('stripe_coupon_id', sa.String(), nullable=False),
    sa.Column('discount_type', sa.String(), nullable=False),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_coupon_id')
    )
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_promo_codes_is_active'), ['is_active'], unique=False)

    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('stripe_payment_method_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_subscriptions_current_period_end'), ['current_period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_subscriptions_current_period_start'), ['current_period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_subscriptions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_subscriptions_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_subscriptions_stripe_subscription_id'), ['stripe_subscription_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('user_promo_code_uses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.Column('discount_applied', sa.Integer(), nullable=False),
    sa.Column('ip_address_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_promo_code_uses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_promo_code_uses_promo_code_id'), ['promo_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_promo_code_uses_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_promo_code_uses_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('article_clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_signature', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('event_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('article_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sources_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_article_clusters_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_clusters_event_signature'), ['event_signature'], unique=False)

    with op.batch_alter_table('challenge_article_assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_article_assignments')
        batch_op.drop_index('idx_assignment_status')
        batch_op.drop_index('idx_user_challenge_assignments')
        batch_op.drop_index('idx_user_daily_assignment')
        batch_op.drop_constraint('uq_user_challenge_day', type_='unique')
        batch_op.create_index(batch_op.f('ix_challenge_article_assignments_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_article_assignments_assignment_date'), ['assignment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_article_assignments_user_challenge_response_id'), ['user_challenge_response_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_article_assignments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('challenge_claims', schema=None) as batch_op:
        batch_op.alter_column('claim_type',
               existing_type=postgresql.ENUM('policy', 'social_issue', 'economic', 'technology', 'environment', 'foreign_policy', 'healthcare', 'education', name='challengeclaimtype'),
               nullable=True)
        batch_op.alter_column('source_topic_ids',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index('idx_claim_controversy')
        batch_op.drop_index('idx_claim_type')
        batch_op.drop_index('idx_weekly_challenge_claims')
        batch_op.create_index(batch_op.f('ix_challenge_claims_weekly_challenge_id'), ['weekly_challenge_id'], unique=False)

    with op.batch_alter_table('challenge_engagements', schema=None) as batch_op:
        batch_op.drop_index('idx_engagement_timing')
        batch_op.drop_index('idx_engagement_type')
        batch_op.drop_index('idx_user_challenge_engagement')
        batch_op.create_index(batch_op.f('ix_challenge_engagements_challenge_assignment_id'), ['challenge_assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_engagements_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.alter_column('provider_data',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('user_challenge_responses', schema=None) as batch_op:
        batch_op.alter_column('agreement_level',
               existing_type=postgresql.ENUM('STRONGLY_DISAGREE', 'DISAGREE', 'NEUTRAL', 'AGREE', 'STRONGLY_AGREE', name='agreementlevel'),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'responded', 'completed', 'skipped', name='challengeresponsestatus'),
               nullable=True,
               existing_server_default=sa.text("'pending'::challengeresponsestatus"))
        batch_op.drop_index('idx_challenge_tracking')
        batch_op.drop_index('idx_response_status')
        batch_op.drop_index('idx_user_selected_claim')
        batch_op.drop_index('idx_user_weekly_response')
        batch_op.drop_constraint('uq_user_weekly_challenge', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_challenge_responses_selected_claim_id'), ['selected_claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_challenge_responses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_challenge_responses_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_challenge_responses_weekly_challenge_id'), ['weekly_challenge_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('trial_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_end', sa.DateTime(), nullable=True))
        batch_op.alter_column('oauth_provider_data',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('passwordless_login_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.create_index(batch_op.f('ix_users_stripe_customer_id'), ['stripe_customer_id'], unique=False)

    with op.batch_alter_table('weekly_challenges', schema=None) as batch_op:
        batch_op.drop_index('idx_active_challenges')
        batch_op.drop_index('idx_challenge_date')
        batch_op.drop_index('idx_challenge_week')
        batch_op.create_index(batch_op.f('ix_weekly_challenges_challenge_date'), ['challenge_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_challenges_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_challenges_week_end_date'), ['week_end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_challenges_week_start_date'), ['week_start_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_challenges_week_start_date'))
        batch_op.drop_index(batch_op.f('ix_weekly_challenges_week_end_date'))
        batch_op.drop_index(batch_op.f('ix_weekly_challenges_is_published'))
        batch_op.drop_index(batch_op.f('ix_weekly_challenges_challenge_date'))
        batch_op.create_index('idx_challenge_week', ['week_start_date', 'week_end_date'], unique=False)
        batch_op.create_index('idx_challenge_date', ['challenge_date'], unique=False)
        batch_op.create_index('idx_active_challenges', ['is_active', 'is_published'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stripe_customer_id'))
        batch_op.alter_column('passwordless_login_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('oauth_provider_data',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('trial_end')
        batch_op.drop_column('trial_start')
        batch_op.drop_column('stripe_customer_id')

    with op.batch_alter_table('user_challenge_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_challenge_responses_weekly_challenge_id'))
        batch_op.drop_index(batch_op.f('ix_user_challenge_responses_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_challenge_responses_status'))
        batch_op.drop_index(batch_op.f('ix_user_challenge_responses_selected_claim_id'))
        batch_op.create_unique_constraint('uq_user_weekly_challenge', ['user_id', 'weekly_challenge_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index('idx_user_weekly_response', ['user_id', 'weekly_challenge_id'], unique=False)
        batch_op.create_index('idx_user_selected_claim', ['user_id', 'selected_claim_id'], unique=False)
        batch_op.create_index('idx_response_status', ['status', 'responded_at'], unique=False)
        batch_op.create_index('idx_challenge_tracking', ['challenge_started_at', 'challenge_completed_at'], unique=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'responded', 'completed', 'skipped', name='challengeresponsestatus'),
               nullable=False,
               existing_server_default=sa.text("'pending'::challengeresponsestatus"))
        batch_op.alter_column('agreement_level',
               existing_type=postgresql.ENUM('STRONGLY_DISAGREE', 'DISAGREE', 'NEUTRAL', 'AGREE', 'STRONGLY_AGREE', name='agreementlevel'),
               nullable=False)

    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.alter_column('provider_data',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('challenge_engagements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_engagements_user_id'))
        batch_op.drop_index(batch_op.f('ix_challenge_engagements_challenge_assignment_id'))
        batch_op.create_index('idx_user_challenge_engagement', ['user_id', 'challenge_assignment_id'], unique=False)
        batch_op.create_index('idx_engagement_type', ['engagement_type', 'created_at'], unique=False)
        batch_op.create_index('idx_engagement_timing', ['created_at', 'engagement_time_seconds'], unique=False)

    with op.batch_alter_table('challenge_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_claims_weekly_challenge_id'))
        batch_op.create_index('idx_weekly_challenge_claims', ['weekly_challenge_id', 'display_order'], unique=False)
        batch_op.create_index('idx_claim_type', ['claim_type'], unique=False)
        batch_op.create_index('idx_claim_controversy', ['controversy_score', 'is_active'], unique=False)
        batch_op.alter_column('source_topic_ids',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('claim_type',
               existing_type=postgresql.ENUM('policy', 'social_issue', 'economic', 'technology', 'environment', 'foreign_policy', 'healthcare', 'education', name='challengeclaimtype'),
               nullable=False)

    with op.batch_alter_table('challenge_article_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_article_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_challenge_article_assignments_user_challenge_response_id'))
        batch_op.drop_index(batch_op.f('ix_challenge_article_assignments_assignment_date'))
        batch_op.drop_index(batch_op.f('ix_challenge_article_assignments_article_id'))
        batch_op.create_unique_constraint('uq_user_challenge_day', ['user_challenge_response_id', 'day_number'], postgresql_nulls_not_distinct=False)
        batch_op.create_index('idx_user_daily_assignment', ['user_id', 'assignment_date'], unique=False)
        batch_op.create_index('idx_user_challenge_assignments', ['user_challenge_response_id', 'day_number'], unique=False)
        batch_op.create_index('idx_assignment_status', ['is_sent', 'is_opened', 'is_clicked'], unique=False)
        batch_op.create_index('idx_article_assignments', ['article_id', 'assignment_date'], unique=False)

    with op.batch_alter_table('article_clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_clusters_event_signature'))
        batch_op.drop_index(batch_op.f('ix_article_clusters_event_date'))
        batch_op.drop_column('last_updated')
        batch_op.drop_column('sources_count')
        batch_op.drop_column('article_count')
        batch_op.drop_column('event_date')
        batch_op.drop_column('event_signature')

    with op.batch_alter_table('user_promo_code_uses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_promo_code_uses_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_promo_code_uses_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_user_promo_code_uses_promo_code_id'))

    op.drop_table('user_promo_code_uses')
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_current_period_start'))
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_current_period_end'))

    op.drop_table('user_subscriptions')
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_codes_is_active'))
        batch_op.drop_index(batch_op.f('ix_promo_codes_code'))

    op.drop_table('promo_codes')
    with op.batch_alter_table('daily_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_usage_date'))

    op.drop_table('daily_usage')
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_plans_stripe_price_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_plans_name'))
        batch_op.drop_index(batch_op.f('ix_subscription_plans_is_active'))

    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
