/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as LoginCallbackRouteImport } from './routes/login.callback'
import { Route as AppSourcesRouteImport } from './routes/_app.sources'
import { Route as AppPrivacyPolicyRouteImport } from './routes/_app.privacy-policy'
import { Route as AppPreferencesRouteImport } from './routes/_app.preferences'
import { Route as AppInsightsRouteImport } from './routes/_app.insights'
import { Route as AppHowItWorksRouteImport } from './routes/_app.how-it-works'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppAnalyzeRouteImport } from './routes/_app.analyze'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppChallengeDateRouteImport } from './routes/_app.challenge.$date'
import { Route as AppArticleIdRouteImport } from './routes/_app.article.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyPolicyRoute = AppPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => AppRoute,
} as any)
const AppPreferencesRoute = AppPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppHowItWorksRoute = AppHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyzeRoute = AppAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengeDateRoute = AppChallengeDateRouteImport.update({
  id: '/challenge/$date',
  path: '/challenge/$date',
  getParentRoute: () => AppRoute,
} as any)
const AppArticleIdRoute = AppArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AppAdminRoute
  '/analytics': typeof AppAnalyticsRoute
  '/analyze': typeof AppAnalyzeRoute
  '/feed': typeof AppFeedRoute
  '/how-it-works': typeof AppHowItWorksRoute
  '/insights': typeof AppInsightsRoute
  '/preferences': typeof AppPreferencesRoute
  '/privacy-policy': typeof AppPrivacyPolicyRoute
  '/sources': typeof AppSourcesRoute
  '/login/callback': typeof LoginCallbackRoute
  '/article/$id': typeof AppArticleIdRoute
  '/challenge/$date': typeof AppChallengeDateRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AppAdminRoute
  '/analytics': typeof AppAnalyticsRoute
  '/analyze': typeof AppAnalyzeRoute
  '/feed': typeof AppFeedRoute
  '/how-it-works': typeof AppHowItWorksRoute
  '/insights': typeof AppInsightsRoute
  '/preferences': typeof AppPreferencesRoute
  '/privacy-policy': typeof AppPrivacyPolicyRoute
  '/sources': typeof AppSourcesRoute
  '/login/callback': typeof LoginCallbackRoute
  '/': typeof AppIndexRoute
  '/article/$id': typeof AppArticleIdRoute
  '/challenge/$date': typeof AppChallengeDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/analyze': typeof AppAnalyzeRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/how-it-works': typeof AppHowItWorksRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/preferences': typeof AppPreferencesRoute
  '/_app/privacy-policy': typeof AppPrivacyPolicyRoute
  '/_app/sources': typeof AppSourcesRoute
  '/login/callback': typeof LoginCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/article/$id': typeof AppArticleIdRoute
  '/_app/challenge/$date': typeof AppChallengeDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/welcome'
    | '/admin'
    | '/analytics'
    | '/analyze'
    | '/feed'
    | '/how-it-works'
    | '/insights'
    | '/preferences'
    | '/privacy-policy'
    | '/sources'
    | '/login/callback'
    | '/article/$id'
    | '/challenge/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/welcome'
    | '/admin'
    | '/analytics'
    | '/analyze'
    | '/feed'
    | '/how-it-works'
    | '/insights'
    | '/preferences'
    | '/privacy-policy'
    | '/sources'
    | '/login/callback'
    | '/'
    | '/article/$id'
    | '/challenge/$date'
  id:
    | '__root__'
    | '/_app'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/welcome'
    | '/_app/admin'
    | '/_app/analytics'
    | '/_app/analyze'
    | '/_app/feed'
    | '/_app/how-it-works'
    | '/_app/insights'
    | '/_app/preferences'
    | '/_app/privacy-policy'
    | '/_app/sources'
    | '/login/callback'
    | '/_app/'
    | '/_app/article/$id'
    | '/_app/challenge/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy-policy': {
      id: '/_app/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof AppPrivacyPolicyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/preferences': {
      id: '/_app/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AppPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/how-it-works': {
      id: '/_app/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof AppHowItWorksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analyze': {
      id: '/_app/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AppAnalyzeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challenge/$date': {
      id: '/_app/challenge/$date'
      path: '/challenge/$date'
      fullPath: '/challenge/$date'
      preLoaderRoute: typeof AppChallengeDateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/article/$id': {
      id: '/_app/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof AppArticleIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAnalyzeRoute: typeof AppAnalyzeRoute
  AppFeedRoute: typeof AppFeedRoute
  AppHowItWorksRoute: typeof AppHowItWorksRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppPreferencesRoute: typeof AppPreferencesRoute
  AppPrivacyPolicyRoute: typeof AppPrivacyPolicyRoute
  AppSourcesRoute: typeof AppSourcesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppArticleIdRoute: typeof AppArticleIdRoute
  AppChallengeDateRoute: typeof AppChallengeDateRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAnalyzeRoute: AppAnalyzeRoute,
  AppFeedRoute: AppFeedRoute,
  AppHowItWorksRoute: AppHowItWorksRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppPreferencesRoute: AppPreferencesRoute,
  AppPrivacyPolicyRoute: AppPrivacyPolicyRoute,
  AppSourcesRoute: AppSourcesRoute,
  AppIndexRoute: AppIndexRoute,
  AppArticleIdRoute: AppArticleIdRoute,
  AppChallengeDateRoute: AppChallengeDateRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LoginRouteChildren {
  LoginCallbackRoute: typeof LoginCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginCallbackRoute: LoginCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
